### ISSUE TITLE
gender

### ISSUE THREAD

**Issue by Ameenekosan** [sxmnc/smircbot#38]
take people's gender in consideration with <3  #nohomo

**Comment by Kiniamaro** [comment]
shouldn't we ask peoples sexual orientation instead and make the message in consequence?

for instance, If I am homosexual, shouldn't the bot say, #noHetero if I'm speaking to a man?


















:^)

**Comment by Ameenekosan** [comment]
well yeah .. and if it is according to the sexual orientation he could say something like '' too cheesy'' or ''get a room''

**Comment by Riboshom** [comment]
Woah woah woah, you guys are going to have the bot use GENDERED pronouns to designate people? That's my trigger!
If that's going to happen, I want support for my preferred pronouns.

**Comment by Ameenekosan** [comment]
Non.  On peu juste changer le message pour les execption donc moi et RainbowHash..  Easy.  Sinon ben la blague de #nohomo cest une façon ridicule de se defendre d'avoir fait des expériences ou d'éviter de se faire juger certains vont même jusqu'à dire '' i sucked his dick  but we said no homo so it's fine "
