### ISSUE TITLE
Permanent storage 

### ISSUE THREAD

**Issue by sm-Fifteen** [sxmnc/smircbot#47]
As things stand, the bot cannot save and load data outside its config file, which it an obstacle that makes it difficult to implement certain features, such as #46 . The core should include a simple key-value storage facility.

**Comment by Kiniamaro** [comment]
yes good idea, we could use something like http://redis.io/ , very fest and straight forward

**Comment by fxleblanc** [comment]
+1 redis

**Comment by jdupl** [comment]
overdesign.com

Why do we need permanent storage: `Tokens should be physical. The only states should be: "when" and "who has committed".` from #46 . Nobody answered.

**Comment by Kiniamaro** [comment]
@jdupl we might not need storage for #46 but it's just a thing we'll need anyways

**Comment by jdupl** [comment]
You guys keep saying "we need it" but we don't **need** it. For chokens, physical tokens are far more reliable than a DB. 
What next ? What is really needed that justifies the handling of a DB. Such bloat. :-1:

**Comment by Kiniamaro** [comment]
:ocean: :ocean: Stop talking about chokens, a DB is useful for lots of stuff, we could get rid of some of the stuff we store inside the config json like the quotes (even though I like them in the config)

**Comment by Kiniamaro** [comment]
also, just noticed we have a bit of code inside the core to handle a sql db, but it doesn't seem to do anything useful yet

**Comment by jdupl** [comment]
Other stuff like what ? 
Chokens are claimed by the choked person. It is his responsibility to ask for the choken.

**Comment by Kiniamaro** [comment]
@jdupl , Typist for instance, or anything we haven't thought of yet

**Comment by sm-Fifteen** [comment]
Ideally, we probably shouldn't need to make a commit to add a quote to the bot's list of quotes, for instance.

**Comment by jdupl** [comment]
So basically sell out the quotes ?

**Comment by Kiniamaro** [comment]
wut?

**Comment by jdupl** [comment]
We agreed that quotes needed *somethings special*.

**Comment by alxgnon** [comment]
Redis isn't permanent storage.

Just use any old SQL solution, the code is already there. Take a look at Maro-kun if you want some examples.

Closing because this is a non-issue.
